---
output: github_document
---

## correspondence 

### 2019-05-03

**RL**  D5 presentation notes.  

2017 2018 and 3 months of 2019 

add a total bar chart of injuries and deaths under each map 

book on R for jounalism from RAL 




### 2019-04-26

**RL**  D4 presentation notes. 

2018 only? can you get data over more years? 

20% above the women,  gray line, to compare to men 

Use sex instead of gender as the legend name (gender has many levels, sex has basically two)  

Image probably needs to change, but not sure how. Possibly an image or collection of images of things you can no longer do when you have oral cancer. 

Image  should illustrate what you think the main point is. 

Omit the legend and label the data mnarker directly. 







### 2019-04-19

**RL**  D3 presentation notes. 

Good work 

Use alpha to make the dots partially transparent 

Try making a finer division on the sizes 

Use a shape = 21 to get a separate color an fill

Account for inflation  

Maybe add a label in each panel for one country in the upper right and one in the lower left 

Maybe substitute a mean for the three years 










### 2019-04-05

**RL**  D2 presentation notes. 

Make the quantitative variable percent of market, or "market share" 

Perhaps ignoring years and instead have two categories: drought and crop, then the quantitative variable is the percent of market for that crop in that drought condition. 

This entails computing the total annual market value of all crops that year then for a given crop and drought condition, summing the crop value, summing the all-crop values over those years with that droughtcondition, then dividing for a percentage. 




### 2019-04-05

**RL**  D2 presentation notes. 



### 2019-03-29

**RL**  D1 presentation notes. 

The introduction you gave us verbally is the basis for a written introduction in the report. 

Are the data current? Can you obtain the winemag.com data yourself to bring it up to date?

I'm not sure binning the wine rating into bad and good is the best way to show the data. I wonder if a different graph design (scatter plot?) would better suit the data. 

A possible addition is a horizontal bar chart to the right that shows the N, number of wines by continent. Later in the term I can help you place the graphs side by side. For now you might try creating a separate display of N. 





### 2019-03-25

**RL** The links on the README page all work. No problems so far. 

I don't see any data. I would have hoped that by now you would have been examining some data for graphing, even if a graph wasn't ready. I can't emphasize enough how important it is that you work ahead on acquiring data that meets the data requirements for the various displays. This is the single most important obstacle that has kept past students from being as successful as they might have been. 

**NH** Thanks for the feedback. I have been working on the first visualization, however I am still working out of my explore file and haven't moved individual parts into carpentry, design, clean data, etc. These will be available shortly.






### 2019-03-10

**RL** I've revised the prompts for the week 2 reading. Please update your reading response file. Remember to complete your responses in writing before class on Tuesday. 
https://github.com/DSR-RHIT/me447-visualizing-data/blob/master/reports/reading-prompts-1.Rmd
      
      

**RL** This is an example of a second comment in reverse chronological order. 

**RD** And its response. 



### 2019-02-10

**RL** I will use this Rmd file for corresponding with you about your portfolio. Entries will be dated and listed in reverse chronological order--that is, with the most recent at the top of the page. You should record your responses directly below, for example: 

**RD** This is a sample response to the comment above.